apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app1 
  name: app1
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    volumeMounts:
    - mountPath: /ubuntu-emptydir
      name: ubuntu-emptydir
    args:
    - sleep
    - "1800"
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /webserver-emptydir
      name: webserver-emptydir
    resources:
      limits:
        cpu: "0.6"
        memory: "128Mi"
      requests:
        cpu: "0.4"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: ubuntu-emptydir
    emptyDir:
      sizeLimit: 256Mi
  - name: webserver-emptydir
    emptyDir:
      sizeLimit: 256Mi
